### ISSUE TITLE
Fatal Error on install

### ISSUE THREAD

**Issue by contemplate** [BrianHenryIE/bh-wc-checkout-rate-limiter#10]
Installed this on a client's site after using it on other client sites with no issue.  It created a fatal error that may have to do with a conflict with Jetpack:

`[11-Oct-2022 02:40:33 UTC] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to BrianHenryIE\Checkout_Rate_Limiter\Admin\Plugins_Page::action_links() must be of the type array, null given, called in /chroot/home/server_name_removed/html/wp-includes/class-wp-hook.php on line 307 and defined in /chroot/home/server_name_removed/html/wp-content/plugins/bh-wc-checkout-rate-limiter/Admin/class-plugins-page.php:57
Stack trace:
#0 /chroot/home/server_name_removed/html/wp-includes/class-wp-hook.php(307): BrianHenryIE\Checkout_Rate_Limiter\Admin\Plugins_Page->action_links(Array, 'bh-wc-checkout-...', NULL, 'all')
#1 /chroot/home/server_name_removed/html/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array)
#2 /chroot/home/server_name_removed/html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/modules/class-callables.php(380): apply_filters('plugin_action_l...', Array, 'bh-wc-checkout-...', NULL, 'all')
#3 /chroot/home/server_name_removed/html/wp-includes/class-wp- in /chroot/home/server_name_removed/html/wp-content/plugins/bh-wc-checkout-rate-limiter/Admin/class-plugins-page.php on line 57`

**Comment by BrianHenryIE** [comment]
I came across the same issue with other plugins I've written previously, but hadn't updated this since (obviously, I'm copying the same code for adding links on the plugins page). I use PHP 7.4's strict typing as widely as possible, and I typed the function with the expected types, then when JetPack invoked the action in its own code and used `null` rather than empty array/string values, the strict-ness caused this error. I've updated to make the function parameters optional.
