### ISSUE TITLE
Logger crashes if unable to write

### ISSUE THREAD

**Issue by patrick-leb** [BrianHenryIE/bh-wc-checkout-rate-limiter#8]
When attempting to use WP-CLI , the command line crashes because it's unable to write the file.
It would probably need a try/catch or another logging location.

```
# sudo -u wpcli wp redis flush
PHP Fatal error:  Uncaught RuntimeException: The file could not be written to. Check that appropriate permissions have been set. in /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/strauss/katzgrau/klogger/src/Logger.php:134
Stack trace:
#0 /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/strauss/brianhenryie/wp-logger/src/includes/class-bh-wp-logger.php(140): BrianHenryIE\Checkout_Rate_Limiter\Katzgrau\KLogger\Logger->__construct()
#1 /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/strauss/brianhenryie/wp-logger/src/class-logger.php(23): BrianHenryIE\Checkout_Rate_Limiter\BrianHenryIE\WP_Logger\includes\BH_WP_Logger->__construct()
#2 /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/strauss/brianhenryie/wp-logger/src/class-logger.php(40): BrianHenryIE\Checkout_Rate_Limiter\BrianHenryIE\WP_Logger\Logger->__construct()
#3 /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/bh-wc-checkout-rate-limiter.php(64): BrianHenryIE\Checkout_Rate_L in /var/www/html/wordpress/web/app/plugins/bh-wc-checkout-rate-limiter/strauss/katzgrau/klogger/src/Logger.php on line 134
```

**Comment by BrianHenryIE** [comment]
Hey, thanks.

I've changed it so it uses the [native WooCommerce logger](https://github.com/woocommerce/woocommerce/blob/164e7e495c123380f1350f97a282c86a2da8a60d/includes/wc-core-functions.php#L1952) now (rather than [KLogger](https://github.com/katzgrau/KLogger)), so hopefully that won't be a problem anymore.

Am I correct to understand that it was working ok as a regular plugin, but only causing a problem when you ran a (unrelated) CLI command? 

I should, as you say, try/catch around that, then add an admin notice ~"chmod /path/to...", but I'm surprised this is a CLI issue and not a general issue. I guess CLI is run under another user than www. 

Let me know if this works for you: https://github.com/BrianHenryIE/bh-wc-checkout-rate-limiter/releases/tag/1.1.0

**Comment by patrick-leb** [comment]
Sorry for the long delay Brian,
the new version fixed it! :) it's perfect!

Yes, it's working perfectly as a regular plugin. The problem showed itself exclusively when using wpcli, which, indeed, is running a different user. 

Thanks!
